// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hello.proto

/*
Package hello is a generated protocol buffer package.

It is generated from these files:
	hello.proto

It has these top-level messages:
	Knock
	Reply
*/
package hello

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// *
// Knock the door or not
type Knock struct {
	Knocked bool `protobuf:"varint,1,opt,name=knocked" json:"knocked,omitempty"`
}

func (m *Knock) Reset()                    { *m = Knock{} }
func (m *Knock) String() string            { return proto.CompactTextString(m) }
func (*Knock) ProtoMessage()               {}
func (*Knock) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Knock) GetKnocked() bool {
	if m != nil {
		return m.Knocked
	}
	return false
}

// *
// Reply based on whether a door was knocked or not.
type Reply struct {
	Reply   bool   `protobuf:"varint,1,opt,name=reply" json:"reply,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=Message" json:"Message,omitempty"`
}

func (m *Reply) Reset()                    { *m = Reply{} }
func (m *Reply) String() string            { return proto.CompactTextString(m) }
func (*Reply) ProtoMessage()               {}
func (*Reply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Reply) GetReply() bool {
	if m != nil {
		return m.Reply
	}
	return false
}

func (m *Reply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Knock)(nil), "hello.Knock")
	proto.RegisterType((*Reply)(nil), "hello.Reply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Hello service

type HelloClient interface {
	// *
	// Determines if you knocked the door and the appropriate
	// reply if you didn't.
	Knocked(ctx context.Context, in *Knock, opts ...grpc.CallOption) (*Reply, error)
}

type helloClient struct {
	cc *grpc.ClientConn
}

func NewHelloClient(cc *grpc.ClientConn) HelloClient {
	return &helloClient{cc}
}

func (c *helloClient) Knocked(ctx context.Context, in *Knock, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := grpc.Invoke(ctx, "/hello.Hello/Knocked", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Hello service

type HelloServer interface {
	// *
	// Determines if you knocked the door and the appropriate
	// reply if you didn't.
	Knocked(context.Context, *Knock) (*Reply, error)
}

func RegisterHelloServer(s *grpc.Server, srv HelloServer) {
	s.RegisterService(&_Hello_serviceDesc, srv)
}

func _Hello_Knocked_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Knock)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloServer).Knocked(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hello.Hello/Knocked",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloServer).Knocked(ctx, req.(*Knock))
	}
	return interceptor(ctx, in, info, handler)
}

var _Hello_serviceDesc = grpc.ServiceDesc{
	ServiceName: "hello.Hello",
	HandlerType: (*HelloServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Knocked",
			Handler:    _Hello_Knocked_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hello.proto",
}

func init() { proto.RegisterFile("hello.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 150 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xce, 0x48, 0xcd, 0xc9,
	0xc9, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x73, 0x94, 0xd4, 0xb9, 0x58, 0xbd,
	0xf3, 0xf2, 0x93, 0xb3, 0x85, 0x24, 0xb8, 0xd8, 0xb3, 0x41, 0x8c, 0xd4, 0x14, 0x09, 0x46, 0x05,
	0x46, 0x0d, 0x8e, 0x20, 0x18, 0xd7, 0x8b, 0x85, 0x83, 0x49, 0x80, 0x59, 0xc9, 0x96, 0x8b, 0x35,
	0x28, 0xb5, 0x20, 0xa7, 0x52, 0x48, 0x84, 0x8b, 0xb5, 0x08, 0xc4, 0x80, 0x2a, 0x83, 0x70, 0x40,
	0xda, 0x7d, 0x53, 0x8b, 0x8b, 0x13, 0xd3, 0x53, 0x25, 0x98, 0x14, 0x18, 0x35, 0x38, 0x83, 0x60,
	0x5c, 0x2f, 0x16, 0x0e, 0x66, 0x01, 0x16, 0x23, 0x03, 0x2e, 0x56, 0x0f, 0x90, 0x85, 0x42, 0xea,
	0x5c, 0xec, 0xde, 0x10, 0x83, 0x85, 0x78, 0xf4, 0x20, 0x0e, 0x02, 0xf3, 0xa5, 0x60, 0x3c, 0xb0,
	0x2d, 0x4a, 0x0c, 0x49, 0x6c, 0x60, 0x77, 0x1a, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x82, 0x97,
	0x43, 0x45, 0xb6, 0x00, 0x00, 0x00,
}
